const DATE_FORMAT = "DD-MM-YYYY";
const DATE_FORMAT_DB = "yyyy-MM-DD HH:mm:ss";
const ALL_STATUS = 0;
const REMAIN_STATUS = 1;
const OVER_DATE_STATUS = 2;
const FAVORITE_STATUS = 3;
const TOKEN = "token";

export default {
    DATE_FORMAT: DATE_FORMAT,
    DATE_FORMAT_DB: DATE_FORMAT_DB,

    ALL_STATUS: ALL_STATUS,
    OVER_DATE_STATUS: OVER_DATE_STATUS,
    REMAIN_STATUS: REMAIN_STATUS,
    FAVORITE_STATUS: FAVORITE_STATUS,

    TOKEN: TOKEN
};
