name: Laravel Tests

on:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
        - laravel: 9
          php: "8.0"
        - laravel: 10
          php: "8.1"

    steps:
    - uses: actions/checkout@v2
    - name: Start docker containers
      run: PHP_VERSION=${{ matrix.php }} docker-compose up -d
    - name: Install dependencies
      run: docker-compose exec -T test composer require --no-interaction "laravel/framework:^${{ matrix.laravel }}.0"
    - name: Run tests
      run: ./test
